name: albertian_wellnest
description: "Albertian Wellnest"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cupertino_http: ^2.0.2
  fetch_client: ^1.1.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.4
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  firebase_storage: ^12.4.4
  flutter_slidable: ^4.0.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  branding: assets/images/sublogo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/sublogo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/loginlogo.png
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
