// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcFRAeGjaKBjtVkiozN_YpyRIDokpTFLA',
    appId: '1:272165471255:web:8c184ae40c149d55e14852',
    messagingSenderId: '272165471255',
    projectId: 'flutter-chat-app-6a177',
    authDomain: 'flutter-chat-app-6a177.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6a177.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYrNvxME3fVuUgrYVp3EleW-zwVE4BgP4',
    appId: '1:272165471255:android:e615c41703bb3138e14852',
    messagingSenderId: '272165471255',
    projectId: 'flutter-chat-app-6a177',
    storageBucket: 'flutter-chat-app-6a177.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPb19mRwjQ0Oo3ue2XCbOOaGF-BLfmizE',
    appId: '1:272165471255:ios:3b65f0d4d846cb0ae14852',
    messagingSenderId: '272165471255',
    projectId: 'flutter-chat-app-6a177',
    storageBucket: 'flutter-chat-app-6a177.firebasestorage.app',
    iosBundleId: 'hari.com.chatApp',
  );

}